app:
  locations:
    url: http://localhost:8081/api/v1/locations/near
  prices:
    url: http://localhost:8082/api/v1/prices
  maps:
    url: https://maps.googleapis.com/maps/api/distancematrix/json
    api-key: <My Google maps key>
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus