kind: Service
apiVersion: v1
metadata:
  name: app
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      name: app
      labels:
        app: app
        version: "latest"
    spec:
      containers:
      - name: app
        image: jsainz/app
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: maps
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    ingress.kubernetes.io/ingress.allow-http: "false"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/client_max_body_size: 200m
    nginx.org/client-max-body-size: 200m
    ingress.bluemix.net/client-max-body-size: 200m
    ingress.bluemix.net/proxy-body-size: 200m
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - gas-stations.us-south.containers.mybluemix.net
    secretName: proxy-sts-tls
  rules:
  - host: gas-stations.us-south.containers.mybluemix.net
    http:
      paths:
      - path: /app
        backend:
          serviceName: app
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: maps
type: Opaque
data:
  GOOGLE_KEY: <API_KEY>